### ISSUE TITLE
Error 500 after installation in TYPO3 12.4.11

### ISSUE THREAD

**Issue by klodeckl** [r3h6/TYPO3.EXT.form_translator#9]
After installing the extension site and backend is down with the following error message:

686261#0: *2716349 FastCGI sent in stderr: "PHP message: PHP Fatal error: Declaration of R3H6\FormTranslator\Command\CreateXliffCommand::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output) must be compatible with Symfony\Component\Console\Command\Command::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output): int in /.../vendor/r3h6/form-translator/Classes/Command/CreateXliffCommand.php on line 42" while reading response header from upstream

On TYPO3 12.4.4 it worked without problems.
PHP 8.2.16

**Comment by ingokasch** [comment]
Same error here on the latest 12.4.14 using form_translator v 2.0.1 via composer

**Comment by r3h6** [comment]
Which version of Symfony Console is installed?
